# Generated by Django 5.2.1 on 2025-05-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bhaskara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('delta', models.IntegerField()),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
            ],
        ),
    ]
